# Python for Data Analysis

Essential Python Libraries:

Numpy

Pandas

scipy

scikit-learn

jupyter notebook


## Numpy

In [0]:
# %load
#with the name of certain python file appended, this command will open the source code of this file.

In [0]:
'''Page 89'''

import numpy as np

arr =np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
arr[9]

9

In [0]:
arr[0:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
arrcopy = arr[0:10].copy()
arrcopy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

randn()

Syntax
X = randn
X = randn(n)
X = randn(sz1,...,szN)
X = randn(sz)
X = randn(___,typename)
X = randn(___,'like',p)
Description
example
X = randn returns a random scalar drawn from the standard normal distribution.

example
X = randn(n) returns an n-by-n matrix of normally distributed random numbers.

example
X = randn(sz1,...,szN) returns an sz1-by-...-by-szN array of random numbers where sz1,...,szN indicate the size of each dimension. For example, randn(3,4) returns a 3-by-4 matrix.

example
X = randn(sz) returns an array of random numbers where size vector sz defines size(X). For example, randn([3 4]) returns a 3-by-4 matrix.

example
X = randn(___,typename) returns an array of random numbers of data type typename. The typename input can be either 'single' or 'double'. You can use any of the input arguments in the previous syntaxes.

example
X = randn(___,'like',p) returns an array of random numbers like p; that is, of the same object type as p. You can specify either typename or 'like', but not both.

In [8]:
'''P97'''

# T for transpose, exchanging the matrix's row with its column


arr = np.random.randn(6,3)
#print(arr) # 3*6
print(arr.T) # 6*3
#print(np.dot(arr.T,arr)) # This is a 3*3 matrix.
#print(np.dot(arr,arr.T)) # This is a 6*6 matrix.

print(arr.T.swapaxes(1,0))


[[ 2.60208441  1.04064647  0.80174776  0.32459053 -0.11777688 -0.09702559]
 [ 0.12586227  0.60525874 -0.90816616 -0.40687525 -1.11961823  0.3814483 ]
 [-1.655034   -1.47030791 -0.86149937  0.67141677  1.6879479  -2.11168652]]
[[ 2.60208441  0.12586227 -1.655034  ]
 [ 1.04064647  0.60525874 -1.47030791]
 [ 0.80174776 -0.90816616 -0.86149937]
 [ 0.32459053 -0.40687525  0.67141677]
 [-0.11777688 -1.11961823  1.6879479 ]
 [-0.09702559  0.3814483  -2.11168652]]


In [9]:
# modf() separates integer and dicemal parts of a float and display them in two arrays.

arr = np.random.randn(7)
print(arr)
print(np.modf(arr))

[-1.21451711  0.38701972  1.38811149  0.33964158 -0.02723705 -0.82307536
 -0.21702111]
(array([-0.21451711,  0.38701972,  0.38811149,  0.33964158, -0.02723705,
       -0.82307536, -0.21702111]), array([-1.,  0.,  1.,  0., -0., -0., -0.]))


In [0]:
''' np.where() , great function! The structure is similar to the IF function in Excel sheets.'''

' np.where() , great function! The structure is similar to the IF function in Excel sheets.'

In [10]:
arr = np.random.randn(5,4)
print(arr)
arr.mean()
print(arr.mean(axis=0)) # get mean of each column
print(arr.mean(axis=1)) # get mean of each row

# It's same about .sort() : axis=0 or 0 means column, axis=1 or 1 means row.

[[ 0.8013664   1.90868299  0.11679848 -1.16868977]
 [-0.66844321 -0.32370811 -0.82218394 -0.98762535]
 [ 1.57053095  0.1431554   0.23019297 -0.88362463]
 [-1.21071046  0.25060524 -0.70049102  0.00767628]
 [ 0.29978328 -1.74293052 -0.35960893 -0.76690155]]
[ 0.15850539  0.047161   -0.30705849 -0.759833  ]
[ 0.41453953 -0.70049015  0.26506367 -0.41322999 -0.64241443]


In [11]:
import random
position = 0 
walk = [position]
steps =1000
for i in range(steps): # xrange() doesn't exist in python 3, use range() instead
    step = 1 if random.randint(0,1) else -1
    position += step
    walk.append(position)
print(walk)

[0, 1, 2, 1, 0, 1, 0, -1, 0, -1, 0, 1, 2, 3, 4, 5, 6, 7, 6, 5, 4, 5, 6, 7, 6, 5, 4, 3, 4, 5, 4, 3, 2, 1, 2, 1, 2, 3, 4, 3, 4, 3, 4, 5, 6, 5, 4, 3, 2, 1, 0, 1, 2, 3, 4, 3, 4, 5, 6, 5, 6, 5, 6, 5, 4, 5, 6, 7, 6, 7, 6, 5, 4, 3, 4, 3, 2, 1, 0, -1, 0, -1, 0, 1, 0, -1, -2, -3, -4, -5, -6, -5, -4, -5, -4, -3, -4, -5, -6, -5, -6, -7, -6, -7, -8, -9, -10, -11, -10, -9, -10, -11, -10, -9, -10, -9, -10, -9, -10, -9, -10, -11, -12, -13, -12, -13, -14, -15, -14, -13, -12, -11, -12, -13, -12, -11, -12, -13, -12, -13, -12, -11, -10, -11, -10, -9, -8, -9, -8, -9, -10, -9, -8, -7, -8, -7, -8, -9, -10, -9, -8, -7, -8, -9, -8, -7, -6, -7, -8, -7, -8, -9, -10, -11, -10, -9, -10, -9, -8, -9, -10, -11, -10, -9, -10, -11, -12, -13, -12, -13, -14, -15, -16, -15, -14, -13, -14, -15, -16, -17, -16, -17, -18, -19, -18, -17, -16, -17, -18, -19, -18, -19, -20, -21, -22, -23, -24, -25, -26, -27, -28, -27, -28, -27, -28, -29, -28, -29, -28, -27, -26, -25, -26, -27, -26, -27, -26, -27, -28, -27, -28, -27, -26, -27, -

## Pandas

In [0]:
from pandas import Series, DataFrame
import pandas as pd

In [0]:
obj = Series([2,5,-9,45,1])
obj

0     2
1     5
2    -9
3    45
4     1
dtype: int64

In [13]:
#dataframe indexing

pop = {'nevada':{2001:2.4,2002:1.5}}

DataFrame(pop, index = pd.Index([2001,2002,2003,2004,2005]))

nevada
2001     2.4
2002     1.5
2003     NaN
2004     NaN
2005     NaN

In [14]:
obj = Series([4.5,3.2,6.7,-5], index = ['d','c','b','a'])
obj

d    4.5
c    3.2
b    6.7
a   -5.0
dtype: float64